[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
bevy_app = { version = "0.16.0-rc.1", default-features = false }
bevy_ecs = { version = "0.16.0-rc.1", default-features = false }
bevy_reflect = { version = "0.16.0-rc.1", default-features = false }
byteorder = { version = "1.5.0", default-features = false}
crossbeam-channel = { version = "0.5.14", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
tokio = { version = "1.44.1", default-features = false }
tokio-util = { version = "0.7.14", default-features = false }
tracing = { version = "0.1", default-features = false }