use bevy::asset::Handle;
use bevy::ecs::system::Resource;
use minecrevy_asset::{
    index::ExtractIndexedAssets,
    mob::{MobCategory, MobType},
};

pub mod villager;

/// All [`MobType`]s in vanilla Minecraft.
#[derive(Resource, ExtractIndexedAssets)]
#[extract(asset = "MobType")]
pub struct MobTypes {
    pub allay: Handle<MobType>,
    pub area_effect_cloud: Handle<MobType>,
    pub armor_stand: Handle<MobType>,
    pub arrow: Handle<MobType>,
    pub axolotl: Handle<MobType>,
    pub bat: Handle<MobType>,
    pub bee: Handle<MobType>,
    pub blaze: Handle<MobType>,
    pub boat: Handle<MobType>,
    pub chest_boat: Handle<MobType>,
    pub cat: Handle<MobType>,
    pub camel: Handle<MobType>,
    pub cave_spider: Handle<MobType>,
    pub chicken: Handle<MobType>,
    pub cod: Handle<MobType>,
    pub cow: Handle<MobType>,
    pub creeper: Handle<MobType>,
    pub dolphin: Handle<MobType>,
    pub donkey: Handle<MobType>,
    pub dragon_fireball: Handle<MobType>,
    pub drowned: Handle<MobType>,
    pub elder_guardian: Handle<MobType>,
    pub end_crystal: Handle<MobType>,
    pub ender_dragon: Handle<MobType>,
    pub enderman: Handle<MobType>,
    pub endermite: Handle<MobType>,
    pub evoker: Handle<MobType>,
    pub evoker_fangs: Handle<MobType>,
    pub experience_orb: Handle<MobType>,
    pub eye_of_ender: Handle<MobType>,
    pub falling_block: Handle<MobType>,
    pub firework_rocket: Handle<MobType>,
    pub fox: Handle<MobType>,
    pub frog: Handle<MobType>,
    pub ghast: Handle<MobType>,
    pub giant: Handle<MobType>,
    pub glow_item_frame: Handle<MobType>,
    pub glow_squid: Handle<MobType>,
    pub goat: Handle<MobType>,
    pub guardian: Handle<MobType>,
    pub hoglin: Handle<MobType>,
    pub horse: Handle<MobType>,
    pub husk: Handle<MobType>,
    pub illusioner: Handle<MobType>,
    pub iron_golem: Handle<MobType>,
    pub item: Handle<MobType>,
    pub item_frame: Handle<MobType>,
    pub fireball: Handle<MobType>,
    pub leash_knot: Handle<MobType>,
    pub lightning_bolt: Handle<MobType>,
    pub llama: Handle<MobType>,
    pub llama_spit: Handle<MobType>,
    pub magma_cube: Handle<MobType>,
    pub marker: Handle<MobType>,
    pub minecart: Handle<MobType>,
    pub chest_minecart: Handle<MobType>,
    pub command_block_minecart: Handle<MobType>,
    pub furnace_minecart: Handle<MobType>,
    pub hopper_minecart: Handle<MobType>,
    pub spawner_minecart: Handle<MobType>,
    pub tnt_minecart: Handle<MobType>,
    pub mule: Handle<MobType>,
    pub mooshroom: Handle<MobType>,
    pub ocelot: Handle<MobType>,
    pub painting: Handle<MobType>,
    pub panda: Handle<MobType>,
    pub parrot: Handle<MobType>,
    pub phantom: Handle<MobType>,
    pub pig: Handle<MobType>,
    pub piglin: Handle<MobType>,
    pub piglin_brute: Handle<MobType>,
    pub pillager: Handle<MobType>,
    pub polar_bear: Handle<MobType>,
    pub tnt: Handle<MobType>,
    pub pufferfish: Handle<MobType>,
    pub rabbit: Handle<MobType>,
    pub ravager: Handle<MobType>,
    pub salmon: Handle<MobType>,
    pub sheep: Handle<MobType>,
    pub shulker: Handle<MobType>,
    pub shulker_bullet: Handle<MobType>,
    pub silverfish: Handle<MobType>,
    pub skeleton: Handle<MobType>,
    pub skeleton_horse: Handle<MobType>,
    pub slime: Handle<MobType>,
    pub small_fireball: Handle<MobType>,
    pub snow_golem: Handle<MobType>,
    pub snowball: Handle<MobType>,
    pub spectral_arrow: Handle<MobType>,
    pub spider: Handle<MobType>,
    pub squid: Handle<MobType>,
    pub stray: Handle<MobType>,
    pub strider: Handle<MobType>,
    pub tadpole: Handle<MobType>,
    pub egg: Handle<MobType>,
    pub ender_pearl: Handle<MobType>,
    pub experience_bottle: Handle<MobType>,
    pub potion: Handle<MobType>,
    pub trident: Handle<MobType>,
    pub trader_llama: Handle<MobType>,
    pub tropical_fish: Handle<MobType>,
    pub turtle: Handle<MobType>,
    pub vex: Handle<MobType>,
    pub villager: Handle<MobType>,
    pub vindicator: Handle<MobType>,
    pub wandering_trader: Handle<MobType>,
    pub warden: Handle<MobType>,
    pub witch: Handle<MobType>,
    pub wither: Handle<MobType>,
    pub wither_skeleton: Handle<MobType>,
    pub wither_skull: Handle<MobType>,
    pub wolf: Handle<MobType>,
    pub zoglin: Handle<MobType>,
    pub zombie: Handle<MobType>,
    pub zombie_horse: Handle<MobType>,
    pub zombie_villager: Handle<MobType>,
    pub zombified_piglin: Handle<MobType>,
    pub player: Handle<MobType>,
    pub fishing_bobber: Handle<MobType>,
}

/// All [`MobCategory`]s in vanilla Minecraft.
#[derive(Resource, ExtractIndexedAssets)]
#[extract(asset = "MobCategory")]
pub struct MobCategories {
    pub monster: Handle<MobCategory>,
    pub creature: Handle<MobCategory>,
    pub ambient: Handle<MobCategory>,
    pub axolotls: Handle<MobCategory>,
    pub underground_water_creature: Handle<MobCategory>,
    pub water_creature: Handle<MobCategory>,
    pub water_ambient: Handle<MobCategory>,
    pub misc: Handle<MobCategory>,
}
