use minecrevy_io_str::{McRead, McWrite};

/// Tells the server to start the login sequence.
#[derive(Clone, PartialEq, Debug, McRead, McWrite)]
pub struct LoginStart {
    /// The player's username.
    #[options(max_len = 16)]
    pub name: String,
}

impl crate::Packet for LoginStart {}

/// Replies to the server to allow packet encryption.
#[derive(Clone, PartialEq, Debug, McRead, McWrite)]
pub struct EncryptionResponse {
    /// The shared secret, encrypted with the server's public key.
    pub shared_secret: Vec<u8>,
    /// The verify token, encrypted with the server's public key.
    pub verify_token: Vec<u8>,
}

impl crate::Packet for EncryptionResponse {}

/// Replies to the server's custom handshake flow.
///
/// See [plugin request][`crate::server::PluginRequestLoginPacket`] for the server side.
#[derive(Clone, PartialEq, Debug, McRead, McWrite)]
pub struct LoginPluginResponse {
    /// Should match the ID generated by the server.
    #[options(varint = true)]
    pub id: i32,
    /// True if the client understands the request, false otherwise. No data follows if false.
    pub successful: bool,
    /// The data being communicated.
    #[options(length = "remaining")]
    pub data: Vec<u8>,
}

impl crate::Packet for LoginPluginResponse {}
