[package]
name = "minecrevy_game"
version = "0.6.0"
edition = "2021"

[dependencies]
# workspace: api
minecrevy_auth = { path = "../../api/auth" }
minecrevy_io_str = { path = "../../api/io_str" }
minecrevy_key = { path = "../../api/key" }
minecrevy_math = { path = "../../api/math" }
minecrevy_protocol_latest = { path = "../../api/protocol_latest" }
minecrevy_text = { path = "../../api/text" }
minecrevy_util = { path = "../../api/util", features = ["bevy"] }
# workspace: server
minecrevy_config = { path = "../config" }
minecrevy_ecs = { path = "../ecs" }
minecrevy_net = { path = "../net" }
# bevy
bevy = { version = "^0.6", default-features = false }
# serialization
serde_json = "^1.0"
hematite-nbt = "^0.5"
enumflags2 = "^0.7"
# utilities
uuid = "^0.8"
nanorand = "^0.7"
flexstr = "^0.9"
once_cell = "^1.10"
